services:
  - type: web
    name: backend-service
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free

  - type: web
    name: frontend-service
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./out
    envVars:
      - key: REACT_APP_API_BASE_URL
        value: https://backend-service.onrender.com
