services:
  - type: web
    name: backend-service
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: PYTHONPATH=./ gunicorn app:app --bind 0.0.0.0:$PORT
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: CORS_ORIGIN
        value: https://cataract-detection-system-1.onrender.com

  - type: web
    name: frontend-service
    env: node
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: free
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://cataract-detection-system.onrender.com